openapi: 3.1.0

info:
    title: SPIT Management API
    description: API quản lý CLB Hỗ trợ Lập trình
    version: 1.0.0
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    contact:
        name: CLB Hỗ trợ Lập trình
        email: clbhtlt.ithusc@gmail.com
        url: https://www.facebook.com/clbhtlt.ithusc/

servers:
    - url: https://localhost:3000/api/v1

tags:
    - name: auth
      description: Xác thực người dùng
    - name: user
      description: Quản lý tài khoản

paths:
    /auth/me:
        get:
            $ref: './swagger/auth/me.yaml'

    /auth/login:
        post:
            $ref: './swagger/auth/login.yaml'

    /auth/refresh_tokens:
        post:
            $ref: './swagger/auth/refresh_tokens.yaml'

    /auth/logout:
        post:
            $ref: './swagger/auth/logout.yaml'

    /users:
        get:
            $ref: './swagger/user/index.yaml'

    /users/{username}:
        post:
            $ref: './swagger/user/show.yaml'
        
        delete:
            $ref: './swagger/user/destroy.yaml'

    #     post:
    #         tags:
    #             - user
    #         summary: Tạo tài khoản
    #         parameters:
    #             - $ref: '#/components/parameters/Authorization'
    #         requestBody:
    #             required: true
    #             content:
    #                 application/json:
    #                     schema:
    #                         type: object
    #                         properties:
    #                             username:
    #                                 type: string
    #                                 example: admin
    #                                 minLength: 6
    #                                 maxLength: 255
    #                             password:
    #                                 type: string
    #                                 example: admin
    #                             repassword:
    #                                 type: string
    #                                 example: admin
    #                             roleId:
    #                                 type: string
    #                                 example: admin
    #         responses:
    #             201:
    #                 description: Tạo tài khoản thành công
    #                 content:
    #                     application/json:
    #                         schema:
    #                             type: object
    #                             properties:
    #                                 message:
    #                                     type: string
    #                                     example: Tạo tài khoản thành công
    #             401:
    #                 $ref: '#/components/responses/Unauthorized'
    #             409:
    #                 description: Tài khoản đã tồn tại
    #                 content:
    #                     application/json:
    #                         schema:
    #                             type: object
    #                             properties:
    #                                 message:
    #                                     type: string
    #                                     example: Tài khoản đã tồn tại
    #             500:
    #                 $ref: '#/components/responses/InternalServer'

components:
    parameters:
        $ref: './swagger/parameters.yaml'

    schemas:
        $ref: './swagger/schemas.yaml'

    responses:
        $ref: './swagger/responses.yaml'